require 'edmunds/api'
require 'edmunds/photo'
require 'edmunds/make'
require 'edmunds/model'
require 'edmunds/model_year'
require 'edmunds/style'

require 'edmunds/equipment'
require 'edmunds/reviews'

require 'edmunds/cost_to_own.rb'
require 'edmunds/edmunds_ratings.rb'
require 'edmunds/incentives.rb'
require 'edmunds/maintenance.rb'
require 'edmunds/market_value.rb'
require 'edmunds/vehicle_ratings.rb'
require 'edmunds/vin.rb'

require 'edmunds/V2/make'
require 'edmunds/V2/model'
require 'edmunds/V2/model_year'
require 'edmunds/V2/style'
require 'edmunds/V2/equipment'
require 'edmunds/V2/engine'

